services:
  backend:
    container_name: backend
    build: ../palmtree/
    environment:
      DATABASE_URL: ${BACKEND_DATABASE_URL}
    networks:
      - palmtree
      - traefik
    restart: unless-stopped
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
    volumes:
      - postgres:/data/postgres
    networks:
      - palmtree
    restart: unless-stopped

networks:
  landing_page:
  traefik_web:
    external: true

volumes:
  postgres:
